nginx:
  container_name: nginx
  image: genee/nginx
  ports:
    - 80:80/tcp
  restart: always
  volumes:
    - ../common/tmp:/tmp
    - ../common/localtime:/etc/localtime:ro
    - ./etc/nginx/default.d:/etc/nginx/default.d:ro
    - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
    - ./etc/nginx/include.d:/etc/nginx/include.d:ro
    - ../..:/data:ro
