node:
  container_name: node
  image: genee/node-dev
  ports:
    - 3000:3000/tcp
  restart: always
  volumes:
    - ../common/localtime:/etc/localtime:ro
    - ../common/tmp:/tmp
    - ../../node:/data/node
  working_dir: /data/node
  command: 
    - sh
    - -c
    - "while true; do sleep 5d; done"
