version: '3'

services:
  mariadb:
    image: mariadb:10.1
    hostname: mariadb.dev
    networks:
      default:
        aliases:
          - mariadb.dev
    ports:
      - 3306:3306/tcp
    volumes:
      - ../common/tmp:/tmp
      - ../common/localtime:/etc/localtime:ro
      - mariadb:/var/lib/mysql
    restart: always

networks:
  default:
    external: 
      name: dev

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=host.docker.internal,hard,nolock,rw"
      device: ":/Volumes/Codes/docker-volumes/mariadb"
