apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 433
      targetPort: 433
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: LoadBalancer
  selector:
    app: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: dev
spec:
  selector:
    subdomain: dev
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        subdomain: dev
    spec:
      hostname: nginx
      subdomain: dev
      restartPolicy: Always
      volumes:
        - name: config
          hostPath:
            path: /Volumes/Codes/data/@stacks
        - name: data
          hostPath:
            path: /Volumes/Codes/data
        - name: nginx
          hostPath:
            path: /Volumes/Codes/data/@stacks/web/nginx
        - name: php
          persistentVolumeClaim:
            claimName: php
      containers:
        - name: nginx
          image: genee/nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /tmp
              name: config
              subPath: common/tmp
            - mountPath: /etc/localtime
              name: config
              subPath: common/localtime
              readOnly: true
            - mountPath: /data
              name: data
              readOnly: true
            - mountPath: /etc/nginx/default.d
              name: nginx
              subPath: etc/nginx/default.d
              readOnly: true
            - mountPath: /etc/nginx/conf.d
              name: nginx
              subPath: etc/nginx/conf.d
              readOnly: true
            - mountPath: /etc/nginx/include.d
              name: nginx
              subPath: etc/nginx/include.d
              readOnly: true
            - mountPath: /var/log/nginx
              name: nginx
              subPath: var/log/nginx
            - mountPath: /data/php
              name: php
              readOnly: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gini
spec:
  selector:
    matchLabels:
      app: gini
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gini
        subdomain: dev
    spec:
      hostname: gini
      subdomain: dev
      restartPolicy: Always
      volumes:
        - name: data
          hostPath:
            path: /Volumes/Codes/data
        - name: config
          hostPath:
            path: /Volumes/Codes/data/@stacks
        - name: gini
          hostPath:
            path: /Volumes/Codes/data/@stacks/web/gini
      containers:
        - name: gini
          image: genee/gini-dev:alpine-39
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /tmp
              name: config
              subPath: common/tmp
            - mountPath: /etc/localtime
              name: config
              subPath: common/localtime
              readOnly: true
            - mountPath: /data
              name: data
            - mountPath: /root/.gitconfig
              name: config
              subPath: .gitconfig
              readOnly: true
            - mountPath: /root/.git-credentials
              name: config
              subPath: .git-credentials
              readOnly: true
            - mountPath: /root/.ssh
              name: config
              subPath: .ssh
              readOnly: true
            - mountPath: /etc/php7/php-fpm.d/www.conf
              name: gini
              subPath: php7.fpm.pool.www.conf
              readOnly: true
            - mountPath: /etc/profile.d/zz_gini.sh
              name: gini
              subPath: profile.gini.sh
              readOnly: true
            - mountPath: /usr/local/share/composer/config.json
              name: gini
              subPath: composer.config.json
              readOnly: true
          workingDir: /data/gini-modules
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
        subdomain: dev
    spec:
      hostname: redis
      subdomain: dev
      restartPolicy: Always
      volumes:
        - name: config
          hostPath:
            path: /Volumes/Codes/data/@stacks
      containers:
        - name: redis
          image: genee/redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /tmp
              name: config
              subPath: common/tmp
            - mountPath: /etc/localtime
              name: config
              subPath: common/localtime
              readOnly: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
        subdomain: dev
    spec:
      hostname: mariadb
      subdomain: dev
      restartPolicy: Always
      volumes:
        - name: data
          hostPath:
            path: /Volumes/Codes/data
        - name: config
          hostPath:
            path: /Volumes/Codes/data/@stacks
        - name: web
          hostPath:
            path: /Volumes/Codes/data/@stacks/web
        - name: database
          persistentVolumeClaim:
            claimName: mariadb
      containers:
        - name: mariadb
          image: genee/mariadb:10.1
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /tmp
              name: config
              subPath: common/tmp
            - mountPath: /etc/localtime
              name: config
              subPath: common/localtime
              readOnly: true
            - mountPath: /etc/my.cnf.d
              name: web
              subPath: mariadb/etc/my.cnf.d
              readOnly: true
            - mountPath: /var/lib/mysql
              name: database
            - mountPath: /var/log/mysql
              name: web
              subPath: mariadb/log